version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "src/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "test/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
