name: Prepare GitHub Release
run-name: Release ${{github.ref_name}} to GitHub by @${{ github.actor }}

on: workflow_dispatch

jobs:
  create_release:
    name: Create Release and Tagged Commit
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release
        uses: SneaksAndData/github-actions/semver_release@v0.1.6
        with:
          major_v: 1
          minor_v: 0
