name: Release to NuGet (Github)
run-name: Release ${{github.ref_name}} to Nuget by @${{ github.actor }}

on: workflow_dispatch

jobs:
  release_to_nuget:
    name: Release distribution to NuGet (private feed)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Package Version
        run: |
          set -e
          version=$(git describe --tags --abbrev=7 | tr -d "v")
          sed -i "s/<Version>0.0.0/<Version>$version/" src/SnD.Sdk.csproj
      - name: Build NuGet
        working-directory: ./src/SnD.Sdk
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -e
          version=$(git describe --tags --abbrev=7 | tr -d "v")
          cd src/
          dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/SneaksAndData/index.json"
          dotnet pack --configuration Release SnD.Sdk.csproj
          dotnet nuget push "bin/Release/SnD.Sdk.$version.nupkg" --source "github"
